resolver: https://raw.githubusercontent.com/input-output-hk/cardano-prelude/00487726c4bc21b4744e59d913334ebfeac7d68e/snapshot.yaml

packages:
  - ./typed-transitions
  - ./typed-protocols
  - ./typed-protocols-cbor
  - ./network-mux
  - ./ouroboros-network
  - ./ouroboros-network-testing
  - ./ouroboros-consensus
  - ./io-sim
  - ./io-sim-classes
  - ./ntp-client
  - ./Win32-network

flags:
  io-sim-classes:
    asserts: true
  network-mux:
    asserts: true
  ouroboros-network:
    asserts: true
  ouroboros-consensus:
    asserts: true

extra-deps:
  - git: https://github.com/input-output-hk/iohk-monitoring-framework
    commit: 156391afaafca6b00d027fb9c03e1bd7a1f03003
    subdirs:
      - contra-tracer

  - git: https://github.com/input-output-hk/cardano-base
    commit: 80deee31f8d9422b8e090e55b17e1a714153180b
    subdirs:
      - binary
      - binary/test
      - cardano-crypto-class
      - slotting

  # Needed for `cardano-ledger-specs`
  - git: https://github.com/input-output-hk/goblins
    commit: 26d35ad52fe9ade3391532dbfeb2f416f07650bc

  - moo-1.2
  - gray-code-0.3.1

  - git: https://github.com/input-output-hk/cardano-ledger
    commit: a773ba71eb9a6fb91dda2cdf6c41b2280f2acf7d
    subdirs:
      - cardano-ledger
      - cardano-ledger/test
      - crypto
      - crypto/test

  - git: https://github.com/input-output-hk/cardano-ledger-specs
    commit: 26d3a60a5d1e13d39e76ddfdd17c4beed6f253ea
    subdirs:
      - byron/chain/executable-spec
      - byron/ledger/executable-spec
      - byron/semantics/executable-spec
      - shelley/chain-and-ledger/dependencies/non-integer
      - shelley/chain-and-ledger/executable-spec

  - git: https://github.com/input-output-hk/cardano-prelude
    commit: 00487726c4bc21b4744e59d913334ebfeac7d68e
    subdirs:
      - .
      - test

  - bimap-0.4.0
  - binary-0.8.7.0
  - generic-monoid-0.1.0.0
  - graphviz-2999.20.0.3
  - hedgehog-quickcheck-0.1.1
  - quickcheck-state-machine-0.6.0
  - splitmix-0.0.2
  - time-units-1.0.0
  - tasty-hedgehog-1.0.0.1
  - Unique-0.4.7.6
  - statistics-linreg-0.3

  # Windows only
  - Win32-2.6.2.0

nix:
  shell-file: nix/stack-shell.nix
